List<String> egyptLocations = [
  'Cairo',
  'Giza',
  'Alexandria',
  'Sharm El-Sheikh',
  'Hurghada',
  'Luxor',
  'Aswan',
  'Tanta',
  'Mansoura',
  'Port Said',
  'Ismailia',
  'Suez',
  'Fayoum',
  'Minya',
  'Assiut',
  'Sohag',
  'Qena',
  'Beni Suef',
  'Damietta',
  'Marsa Matruh',
  'El-Arish',
  'Dahab',
  'Siwa Oasis',
  'El Gouna',
  'Ain Sokhna',
  'Saint Catherine',
  'El-Minya',
  'New Cairo',
  '6th of October City',
  'Sheikh Zayed City',
  'Al-Alamein',
  'Red Sea Governorate',
  'North Coast (Sahel)',
  'Kom Ombo',
  'Edfu',
  'Abu Simbel',
  'Wadi El Natrun',
  'Ras Ghareb',
  'Nuweiba',
  'Safaga',
];
